/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package asm001;

public class App {

    private String message;
    public void getGreeting() {
         this.message = "Hello World!";
    }

    public void hello() {
        System.out.println(this.message);
    }
    public static void main(String[] args) {
        System.out.println("message");
    }
}
